### ISSUE TITLE
Error importing heatmap.py module 

### ISSUE THREAD

**Issue by mayeshh** [multispot-software/multispot_utils#2]
I cloned the `multipsot_utils` repo for the analysis that I've been working on. It was not working perfectly, for example `info_html(d)` has not been working for me. However, I was able to import the heatmap module without trouble. I do not know what has changed, but yesterday when I tried to run my notebook I am now getting the error: `ImportError: attempted relative import with no known parent package`. 

I have tried deleting and re-installing the `multispot_utils` repo, but this doesn't solve my problem. 

I have also tried moving the the multispot utility scripts directly into my working directory, but this doesn't help either. In the past, I recall having just the two scripts, `heatmap.py` and `manta48.py` and everything working including `info_html()`. Which scripts are necessary, or what are the dependencies? 

Another thing I tried is cloning the `multispot_utils` repo into my local copy of the FRETBursts folder. This doesn't fix the error either. 

Currently, I have the `multispot_utils` repo in Users/maya/software/multispot_utils where FRETBursts is also located, and the issue still persists. 

Here is the traceback:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-138599ce7167> in <module>
      6 import matplotlib as mpl
      7 import matplotlib.pyplot as plt
----> 8 from heatmap import heatmap48, spotsh, spotsv
      9 import pybroom as br`

`~/Documents/weiss_lab/48-spot/multispot_review_results/heatmap.py in <module>
      3 import seaborn as sns
      4 
----> 5 from .manta48 import spotsv
      6 
      7 `
`ImportError: attempted relative import with no known parent package`. 
```

**Comment by tritemio** [comment]
@mayeshh, you may have found a bug, but I also see weird stuff in your error. 

I write you what I did, so you may understand how to fix these problems.

First I checked the `multispot_utils` package in a new environment:

```
conda create -n py37-sm python=3.7
conda activate py37-sm
conda install fretbursts
pip install pybroom
pip install git+https://github.com/multispot-software/multispot_utils.git
```

The last command installs the package `multispot_utils` from github (that's how you can do if the package is not published on PyPI).

Then I launched ipython and tried:

```python
In [1]: import multispot_utils                                                                                                    
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bceb21d7ece9> in <module>
----> 1 import multispot_utils

~/miniconda3/envs/py37-sm/lib/python3.7/site-packages/multispot_utils/__init__.py in <module>
----> 1 from manta48 import spotsh, spotsv
      2 from .heatmap import heatmap48
      3 from .utils import info_html
      4 
      5 from ._version import get_versions

ModuleNotFoundError: No module named 'manta48'
```
Ok, same error as you (but note the path, it is not trying to import a local folder but from the environment folder). I think the import line (1) should be `.manta48`, the `.` means import the module from the same folder as the current file (the current file is __init__.py).

To try the fix I reinstall `multispot_utils` from sources in editable mode:

```
cd ~/src
git clone https://github.com/multispot-software/multispot_utils.git
cd multispot_utils/
pip install -e .
cd ~
```

Then, from ipython:

```python
In [1]: import multispot_utils                                                                                                    
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bceb21d7ece9> in <module>
----> 1 import multispot_utils

~/src/multispot_utils/multispot_utils/__init__.py in <module>
----> 1 from manta48 import spotsh, spotsv
      2 from .heatmap import heatmap48
      3 from .utils import info_html
      4 
      5 from ._version import get_versions

ModuleNotFoundError: No module named 'manta48'
```

Same error, but note the path is a "local" path, not the environment dir as before. Finally I edited the __init__.py and added the `.`, this fixed the import.

Now, back to your error. Once importing multispot_utils is fixed, you may want to change your code (presumably in a notebook?) from:

```python
from heatmap import heatmap48, spotsh, spotsv
```
 to:

```python
from multispot_utils import heatmap48, spotsh, spotsv
```

**Comment by tritemio** [comment]
@mayeshh, I committed the change (added a `.`). Let me know if you have more errors.

**Comment by tritemio** [comment]
@mayeshh, I forgot to add: the "weird stuff" in your error is that it is trying to import heatmat from the local folder (presumably the same folder as the notebook). There should be no `manta48.py` or heatmap.py` file in the notebook folder as these files will be imported from the multispot_utils package.
